/* Sterling You — shared location dataset (Bangladesh divisions/districts/thanas/areas) */
window.locationData = {
            "Dhaka": {
                "Dhaka": {
                    // Replace your existing Dhaka > Dhaka section entries with these additions/fixes:

"Banani": ["Banani", "Banani Block A", "Banani Block B", "Banani Block C", "Banani Block D", "Banani Block E", "Banani Block F", "Banani Block G", "Banani Block H", "Banani Block I", "Banani Block J", "Banani Block K", "Banani DOHS", "Banani Chairmanbari", "Banani Road 11", "Banani Road 17", "Banani Bazar"],
"Mohakhali": ["Mohakhali", "Mohakhali DOHS", "Mohakhali Wireless Gate", "Mohakhali Bus Stand", "Mohakhali Bazar", "Mohakhali Rail Gate", "Niketon", "Natun Bazar", "Aminbazar", "Kamal Ataturk Avenue"],
"Cantonment": ["Cantonment", "Dhaka Cantonment", "Cantonment DOHS", "Shaheed Sarani", "Airport Road", "Khilkhet", "Nikunja 1", "Nikunja 2", "Kurmitola", "Ashkona", "Diabari"],
"Uttara": ["Uttara", "Uttara Sector 1", "Uttara Sector 2", "Uttara Sector 3", "Uttara Sector 4", "Uttara Sector 5", "Uttara Sector 6", "Uttara Sector 7", "Uttara Sector 8", "Uttara Sector 9", "Uttara Sector 10", "Uttara Sector 11", "Uttara Sector 12", "Uttara Sector 13", "Uttara Sector 14", "Uttara West", "Uttara East", "Uttara Model Town", "Azampur", "Rajlakshmi", "Abdullahpur", "Baitul Aman Housing", "Uttara 3rd Phase"],
"Pallabi": ["Pallabi", "Mirpur 11", "Mirpur 11.5", "Mirpur 12", "Mirpur 13", "Mirpur 14", "Mirpur DOHS", "Duaripara", "Katasur", "Paikpara", "Gabtoli", "Shewrapara", "Kazipara", "Bauniabadh"],
"Kafrul": ["Kafrul", "Ibrahimpur", "Kachukhet", "Senpara Parbata", "Monipuripara", "Bhasantek", "Taltola", "Agargaon", "Pirerbagh", "Secretariat Quarter", "Lalmatia Block A", "Lalmatia Block B", "Lalmatia Block C", "Lalmatia Block D", "Lalmatia Block E", "Lalmatia Block F", "Lalmatia Block G"],
"Hatirjheel": ["Hatirjheel", "Rampura", "East Rampura", "West Rampura", "Banasree", "Banasree Block A", "Banasree Block B", "Banasree Block C", "Banasree Block D", "Banasree Block E", "Meradia", "Mugda", "North Mugda", "South Mugda", "Mahanagar Project", "Ulon"],
"Gulshan": ["Gulshan", "Gulshan 1", "Gulshan 2", "Gulshan Avenue", "Gulshan Circle 1", "Gulshan Circle 2", "Gulshan North", "Gulshan South", "Gulshan Lake Road", "Gulshan Model Town", "Gulshan Pink City", "DNCC Market", "Niketan", "Baridhara Diplomatic Zone", "Police Plaza"],
"Baridhara": ["Baridhara", "Baridhara DOHS", "Baridhara Block J", "Baridhara Block K", "Baridhara Diplomatic Zone", "Progati Sarani", "Shahjadpur", "Vatara", "Nordic Club Area", "Notun Bazar"],
"Tejgaon": ["Tejgaon", "Tejgaon Industrial Area", "Farmgate", "Bijoy Sarani", "Kawran Bazar", "West Nakhalpara", "East Nakhalpara", "Indira Road", "Monipur", "Tejkunipara", "Tejgaon Link Road", "Wireless Gate", "Mogbazar Rail Gate", "Sonargaon Hotel Area"],
"Shahbagh": ["Shahbagh", "Shahbagh Crossing", "Aziz Market", "TSC", "Doel Chattar", "Nilkhet", "Elephant Road", "Science Lab", "New Market", "Paribagh", "Dhaka University Area", "High Court"],
"Motijheel": ["Motijheel", "Motijheel C/A", "Dilkusha C/A", "Shapla Chattar", "Arambagh", "Kakrail", "Segunbagicha", "Rajarbagh", "Purana Paltan", "Naya Paltan", "Fakirerpool", "Bijoy Nagar", "Kamalapur", "Toyenbee Circular Road"],
"Paltan": ["Purana Paltan", "Naya Paltan", "Bijoy Nagar", "Kakrail", "Segunbagicha", "Inner Circular Road", "VIP Road"],
"Ramna": ["Ramna", "Baily Road", "Eskaton", "New Eskaton", "Old Eskaton", "Moghbazar", "Shantinagar", "Siddheswari", "Minto Road", "Topkhana Road", "Maghbazar Wireless", "Bijoynagar"],
"Dhanmondi": ["Dhanmondi", "Dhanmondi 1", "Dhanmondi 2", "Dhanmondi 3", "Dhanmondi 4", "Dhanmondi 5", "Dhanmondi 6", "Dhanmondi 7", "Dhanmondi 8", "Dhanmondi 9", "Dhanmondi 10", "Dhanmondi 11", "Dhanmondi 12", "Dhanmondi 13", "Dhanmondi 14", "Dhanmondi 15", "Dhanmondi 16", "Dhanmondi 17", "Dhanmondi 18", "Dhanmondi 27", "Dhanmondi 32", "Satmasjid Road", "Mirpur Road", "Lake Circus", "Jigatola", "Shangkar", "Rayer Bazar", "Sobhanbag", "Panthapath", "Free School Street", "Sukrabad"],
"Mohammadpur": ["Mohammadpur", "Mohammadpur Bus Stand", "Mohammadpur Krishi Market", "Mohammadpur Town Hall", "Geneva Camp", "Adabor", "Shekhertek", "Nurjahan Road", "Tajmahal Road", "Jahanara Garden", "PC Culture Housing", "Shahed Colony", "Basila", "Katashur", "Dhaka Udyan", "Bajdhar Para", "Rahmatullah Nagar", "Japan Garden City"],
"Lalbagh": ["Lalbagh", "Azimpur", "Azimpur Colony", "Dhakeshwari", "Pilkhana", "Nawabganj", "Imamganj", "Begum Bazar", "Shankhari Bazar", "Lalbagh Fort Area"],
"Chawkbazar": ["Chawkbazar", "Begum Bazar", "Shankhari Bazar", "Islampur", "Urdu Road", "Mitford", "Bangsal"],
"Kotwali": ["Kotwali", "Babubazar", "Nawabpur", "Patuatuli", "Sadarghat", "Mitford", "Bangsal", "Firingi Bazar", "Boro Pool", "Jubilee Road", "Asadganj"],
"Wari": ["Wari", "Tikatuli", "Gopibagh", "Dholaikhal", "Baldha Garden", "Joy Kali Temple Road", "Rankin Street", "Faridabad", "Laxmibazar", "Narinda"],
"Sutrapur": ["Sutrapur", "Faridabad", "Laxmibazar", "Narinda", "Wari", "Gendaria", "Dinnath Sen Road"],
"Gendaria": ["Gendaria", "Dinnath Sen Road", "Sadhana Oushadhalaya", "Narinda", "Swamibagh", "Banagram"],
"Jatrabari": ["Jatrabari", "Jatrabari Chowrasta", "Dholairpar", "Danialpara", "Kutubkhali", "Rayerbagh", "Shanir Akhra", "Postogola", "Kanchpur Bridge Area", "Donia", "Katherpool"],
"Demra": ["Demra", "Signboard", "Shanir Akhra", "Matuail", "Sarulia", "Konapara", "Demra Bazar", "Demra Staff Quarter", "Kholamora"],
"Sabujbagh": ["Sabujbagh", "Basabo", "Madartek", "Mugdapara", "Kamalapur", "Madhubagh", "Maniknagar", "Goran", "Razarbagh"],
"Khilgaon": ["Khilgaon", "Khilgaon Chowdhurypara", "Khilgaon Taltola", "Khilgaon Railgate", "Tilpapara", "Goran", "North Goran", "South Goran", "Bashabo", "North Bashabo", "South Bashabo", "Maniknagar", "Nandipara", "Sipahibagh"],
"Rampura": ["Rampura", "East Rampura", "West Rampura", "Banasree", "TV Center", "Wapda Road", "Ulon"],
"Mirpur": ["Mirpur 1", "Mirpur 2", "Mirpur 6", "Mirpur 7", "Mirpur 10", "Mirpur 10 Golchattar", "Mirpur 11", "Mirpur 11.5", "Mirpur 12", "Mirpur 13", "Mirpur 14", "Mirpur Ceramic", "Mirpur Zoo", "Mirpur Stadium", "Mirpur Beribadh", "Kalshi", "Rupnagar", "Senpara Parbata", "Tollarbag", "Duaripara", "East Monipur", "West Monipur", "Pirerbagh", "Kazipara", "Shewrapara", "Paikpara", "Bauniabadh", "Section 6", "Section 7", "Section 10", "Section 11", "Section 12"],
"Adabor": ["Adabor", "Baitul Aman Housing", "Mohammadia Housing", "Shyamoli", "Shyamoli Housing", "Ring Road"],
"Sher-e-Bangla Nagar": ["Sher-e-Bangla Nagar", "Agargaon", "Taltola", "Sher-e-Bangla Krishi Bishwavidyalay", "National Assembly Area"],
"Kalabagan": ["Kalabagan", "Bashiruddin Road", "Green Road", "Kathalbagan", "Free School Street"],
"New Market": ["New Market", "Azimpur", "Elephant Road", "Science Lab", "Nilkhet", "Chandni Chowk"],
"Hazaribagh": ["Hazaribagh", "Rayerbazar", "Jigatola", "Lalbagh Road", "Tannery Area"],
"Kamrangirchar": ["Kamrangirchar", "Ashrafabad", "Kholamora", "Nawabganj", "Char Kamrangirchar"],
"Keraniganj": ["Keraniganj", "Aganagar", "Ati Bazar", "Chunakhali", "Jinjira", "Kalindi", "Ruhitpur", "Taranagar", "Shubhadya", "Bochila", "Zinzira Bazar", "Sarulia", "Rokeya Nagar", "Kalatia", "Subhadia", "Hrinagar"],
"Savar": ["Savar", "Aminbazar", "Ashulia", "Bank Town", "Bipail", "Hemayetpur", "Jahangirnagar University", "Nabinagar", "Savar Bazar", "Nishchintopur", "Vogra", "Balipara", "Ghoshbag", "Tetuljhora", "Pathalia", "Savar EPZ", "Rajfulbaria", "Bypass Road Savar"],
"Dakshinkhan": ["Dakshinkhan", "Ashkona", "Azampur", "Chalaband", "Faidabad", "Gawair", "Kanchkura", "Mollartek"],
"Uttarkhan": ["Uttarkhan", "Atipara", "Chamurkhan", "Kachkura", "Maziara", "Uzampur", "Harirampur"],
"Vatara": ["Vatara", "Bashundhara R/A", "Beraid", "Kuril", "Nurer Chala", "Solmaid", "Nadda", "Kalachadpur", "Notun Bazar", "Boro Beraid", "Joar Sahara", "Kuratoli"],
"Khilkhet": ["Khilkhet", "Dumni", "Kuril", "Lake City Concord", "Nikunja 1", "Nikunja 2", "Pink City", "Joar Sahara", "Kuratoli"],
"Bimanbandar": ["Airport Area", "Hajj Camp", "Kawnia", "Zia Colony"],
"Turag": ["Turag", "Baunia", "Diabari", "Kamarpara", "Tongi"],
"Darus Salam": ["Darus Salam", "Kallyanpur", "Gabtoli", "Mirpur Road"],
"Shah Ali": ["Shah Ali Bagh", "Mirpur 1", "Duaripara"],
"Shyampur": ["Shyampur", "Dholaipar", "Jurain", "Kadamtali", "Muradpur"],
"Kadamtali": ["Kadamtali", "Jurain", "Muradpur", "Shyampur", "Donia"],
"Bhashantek": ["Bhashantek", "Dewanpara", "Vasantek Cantonment"],
                },
                "Faridpur": ["Alfadanga", "Bhanga", "Boalmari", "Charbhadrasan", "Faridpur Sadar", "Madhukhali", "Nagarkanda", "Sadarpur", "Saltha"],
                "Gazipur": {
                    "Gazipur Sadar": ["Board Bazar", "Chandana Chowrasta", "Gazipur City", "Joydebpur", "Kashimpur", "Konabari", "Salna", "Shibbari"],
                    "Tongi": ["Tongi Bazar", "Aushpara", "Cherag Ali", "Ershad Nagar", "Hossain Market", "Morkun", "Station Road"],
                    "Kaliakair": ["Kaliakair", "Chandra", "Mouchak", "Shafipur"],
                    "Kaliganj": ["Kaliganj"],
                    "Kapasia": ["Kapasia"],
                    "Sreepur": ["Sreepur", "Bhaluka", "Maona"]
                },
                "Gopalganj": ["Gopalganj Sadar", "Kashiani", "Kotalipara", "Muksudpur", "Tungipara"],
                "Kishoreganj": ["Austagram", "Bajitpur", "Bhairab", "Hossainpur", "Itna", "Karimganj", "Katiadi", "Kishoreganj Sadar", "Kuliarchar", "Mithamain", "Nikli", "Pakundia", "Tarail"],
                "Madaripur": ["Kalkini", "Madaripur Sadar", "Rajoir", "Shibchar"],
                "Manikganj": ["Daulatpur", "Ghior", "Harirampur", "Manikganj Sadar", "Saturia", "Shivalaya", "Singair"],
                "Munshiganj": ["Gazaria", "Lohajang", "Munshiganj Sadar", "Sirajdikhan", "Sreenagar", "Tongibari"],
                "Narayanganj": {
                    "Narayanganj Sadar": ["Chashara", "Deobhog", "Golgachia", "Mandalpara", "Nitaiganj", "Tanbazar"],
                    "Fatullah": ["Fatullah", "Bhuigar", "Enayetnagar", "Pagla", "Panchabati", "Shibu Market"],
                    "Siddhirganj": ["Siddhirganj", "Adamjee", "Baghpara", "Kanchpur", "Mouchak", "Signboard", "Sanarpar"],
                    "Araihazar": ["Araihazar"],
                    "Bandar": ["Bandar", "Madanpur", "Nabiganj"],
                    "Rupganj": ["Rupganj", "Bhulta", "Kanchan", "Murapara", "Tarabo"],
                    "Sonargaon": ["Sonargaon", "Kanchpur", "Mograpara"]
                },
                "Narsingdi": ["Belabo", "Monohardi", "Narsingdi Sadar", "Palash", "Raipura", "Shibpur"],
                "Rajbari": ["Baliakandi", "Goalandaghat", "Kalukhali", "Pangsha", "Rajbari Sadar"],
                "Shariatpur": ["Bhedarganj", "Damudya", "Gosairhat", "Naria", "Shariatpur Sadar", "Zajira"],
                "Tangail": ["Basail", "Bhuapur", "Delduar", "Dhanbari", "Ghatail", "Gopalpur", "Kalihati", "Madhupur", "Mirzapur", "Nagarpur", "Sakhipur", "Tangail Sadar"]
            },
            "Chattogram": {
                "Bandarban": ["Alikadam", "Bandarban Sadar", "Lama", "Naikhongchhari", "Rowangchhari", "Ruma", "Thanchi"],
                "Brahmanbaria": ["Akhaura", "Ashuganj", "Bancharampur", "Bijoynagar", "Brahmanbaria Sadar", "Kasba", "Nabinagar", "Nasirnagar", "Sarail"],
                "Chandpur": ["Chandpur Sadar", "Faridganj", "Haimchar", "Haziganj", "Kachua", "Matlab Dakshin", "Matlab Uttar", "Shahrasti"],
                "Chattogram": {
                    "Anwara": ["Anwara"],
                    "Banshkhali": ["Banshkhali"],
                    "Boalkhali": ["Boalkhali"],
                    "Chandanaish": ["Chandanaish"],
                    "Fatikchhari": ["Fatikchhari"],
"Hathazari": ["Hathazari", "Aman Bazar", "Fatehabad", "Gorduara", "Hamidchar", "Mirsharai Bazar"],                    
"Karnaphuli": ["Karnaphuli"],
                    "Lohagara": ["Lohagara"],
                    "Mirsharai": ["Mirsharai"],
                    "Patiya": ["Patiya"],
                    "Rangunia": ["Rangunia"],
                    "Raozan": ["Raozan"],
                    "Sandwip": ["Sandwip"],
                    "Satkania": ["Satkania"],
                    "Sitakunda": ["Sitakunda", "Bhatiari", "Faujdarhat", "Baraiyadhala", "Kumira", "Salimpur", "Shitakundo Bazar", "Barabkunda", "Fouzdarhat Beach"],
                    "Akbar Shah": ["Akbar Shah", "Firoz Shah Colony", "Biswa Colony"],
                    "Bakalia": ["Bakalia", "Chaktai", "Kalamia Bazar", "Rahattar Pool"],
                    "Bandar": ["Bandar", "Gosaildanga", "Nimtala"],
                    "Bayazid": ["Bayazid Bostami", "Oxygen", "Sher Shah Colony", "Baizid Link Road", "Sugandha", "CDA Avenue", "Baizid Bostami Road", "Foy's Lake Area", "Khulshi Hill"],
                    "Chandgaon": ["Chandgaon", "Bahaddarhat", "Kalurghat", "Mohra", "Chandgaon R/A", "Muradpur", "Hazi Colony", "East Nasirabad", "Bayazid Bostami Road"],
                    "Chawkbazar": ["Chawkbazar", "Jamal Khan", "Kapasgola", "Katalganj", "Devpahar"],
                    "Double Mooring": ["Double Mooring", "Agrabad", "Agrabad Access Road", "Choumuhani", "Dewanhat", "Munsurabad", "CDA Commercial Area", "Segun Bagicha"],
                    "EPZ": ["EPZ", "Cement Crossing", "Free Port"],
                    "Halishahar": ["Halishahar", "Boroipara", "Naya Bazar", "Shantibag", "Halishahar Housing Estate", "Block A", "Block B", "Block C", "Block D", "Block E", "Block F", "Block G", "Port Connecting Road"],
                    "Khulshi": ["Khulshi", "GEC", "Jhautala", "Lalkhan Bazar", "Nasirabad", "Zakir Hossain Road"],
                    "Kotwali": ["Kotwali", "Anderkilla", "Khatunganj", "New Market", "Reazuddin Bazar", "Station Road", "Chawk Bazar", "Firingi Bazar", "Boro Pool", "Jubilee Road", "Asadganj"],
                    "Pahartali": ["Pahartali", "AK Khan", "Alangkar", "Colonel Hat", "Oxygen", "CDA Avenue", "Baizid Link Road", "Nasirabad Housing", "Zakir Hossain Road"],
                    "Panchlaish": ["Panchlaish", "2 No Gate", "Muradpur", "Sholashahar", "GEC Circle", "Probortak Circle", "Wasa Mor", "Dampara", "Nasirabad", "Surma"],
                    "Patenga": ["Patenga", "Kathgar", "Potenga Sea Beach Area", "Steel Mill"],
                    "Sadarghat": ["Sadarghat", "Majhirghat"]
                },
                "Cox's Bazar": ["Chakaria", "Cox's Bazar Sadar", "Kutubdia", "Maheshkhali", "Pekua", "Ramu", "Teknaf", "Ukhia", "Cox's Bazar Beach", "Kolatoli", "Sugandha Beach", "Laboni Beach", "Himchhari", "Inani", "Baharchhara", "Jhilongjha"],
                "Cumilla": ["Barura", "Brahmanpara", "Burichang", "Chandina", "Chauddagram", "Cumilla Sadar", "Daudkandi", "Debidwar", "Homna", "Laksam", "Lalmai", "Manoharganj", "Meghna", "Muradnagar", "Nangalkot", "Titas"],
                "Feni": ["Chhagalnaiya", "Daganbhuiyan", "Feni Sadar", "Fulgazi", "Parshuram", "Sonagazi"],
                "Khagrachhari": ["Dighinala", "Khagrachhari Sadar", "Lakshmichhari", "Mahalchhari", "Manikchhari", "Matiranga", "Panchhari", "Ramgarh"],
                "Lakshmipur": ["Kamalnagar", "Lakshmipur Sadar", "Raipur", "Ramganj", "Ramgati"],
                "Noakhali": ["Begumganj", "Chatkhil", "Companiganj", "Hatiya", "Kabirhat", "Noakhali Sadar", "Senbagh", "Sonaimuri", "Subarnachar"],
                "Rangamati": ["Baghaichhari", "Barkal", "Belaichhari", "Juraichhari", "Kaptai", "Kawkhali", "Langadu", "Naniarchar", "Rajasthali", "Rangamati Sadar"]
            },
"Sylhet": {
    "Habiganj": ["Ajmiriganj", "Bahubal", "Baniachong", "Chunarughat", "Habiganj Sadar", "Lakhai", "Madhabpur", "Nabiganj"],
    "Moulvibazar": {
        "Barlekha": ["Barlekha"],
        "Juri": ["Juri"],
        "Kamalganj": ["Kamalganj"],
        "Kulaura": ["Kulaura"],
        "Moulvibazar Sadar": ["Moulvibazar Sadar"],
        "Rajnagar": ["Rajnagar"],
        "Sreemangal": ["Sreemangal", "Sreemangal Town", "Tea Garden Area", "Bhanu Beel", "Lawachara", "Kalapur"]
    },
    "Sunamganj": ["Bishwamvarpur", "Chhatak", "Dakshin Sunamganj", "Derai", "Dharmapasha", "Dowarabazar", "Jagannathpur", "Jamalganj", "Sullah", "Sunamganj Sadar", "Tahirpur"],
    "Sylhet": {
        "Balaganj": ["Balaganj"],
        "Beanibazar": ["Beanibazar"],
        "Bishwanath": ["Bishwanath"],
        "Companiganj": ["Companiganj"],
        "Dakshin Surma": ["Dakshin Surma", "Chandipool", "Humayun Rashid Chottor", "Kadamtali", "Khadim Nagar"],
        "Fenchuganj": ["Fenchuganj"],
        "Golapganj": ["Golapganj"],
        "Gowainghat": ["Gowainghat"],
        "Jaintiapur": ["Jaintiapur"],
        "Kanaighat": ["Kanaighat"],
        "Osmani Nagar": ["Osmani Nagar"],
        "Sylhet Sadar": ["Sylhet Sadar", "Akhalia", "Amberkhana", "Bandar Bazar", "Chouhatta", "Dargah Mahalla", "Lamabazar", "Mirboxtola", "Pathantula", "Shibganj", "Subidbazar", "Tilagarh", "Uposhohor", "Zindabazar", "Airport Road", "Kumarpara", "Shahjalal Upashahar", "Modina Market", "Bondor Bazar", "Kazir Bazar", "Taltola", "Mendibagh", "Nayasarak", "Rekabi Bazar"],
        "Zakiganj": ["Zakiganj"]
    }
},
            "Khulna": {
                "Bagerhat": ["Bagerhat Sadar", "Chitalmari", "Fakirhat", "Kachua", "Mollahat", "Mongla", "Morrelganj", "Rampal", "Sarankhola"],
                "Chuadanga": ["Alamdanga", "Chuadanga Sadar", "Damurhuda", "Jibannagar"],
                "Jashore": ["Abhaynagar", "Bagherpara", "Chaugachha", "Jashore Sadar", "Jhikargachha", "Keshabpur", "Manirampur", "Sharsha", "Jashore Town", "Rail Gate", "Mujib Sarani", "Chanchra", "Benapole"],
                "Jhenaidah": ["Harinakunda", "Jhenaidah Sadar", "Kaliganj", "Kotchandpur", "Maheshpur", "Shailkupa"],
                "Khulna": ["Batiaghata", "Dacope", "Dumuria", "Dighalia", "Koyra", "Paikgacha", "Phultala", "Rupsa", "Terokhada", "Khulna Sadar", "Sonadanga", "Boyra", "Khalishpur", "Khan Jahan Ali Road", "Shiromoni", "Daulatpur", "Fulbarigate", "Nirala", "Gollamari", "Tutpara", "Mujgunni", "Hadis Park Area", "KDA Avenue", "Ferri Ghat"],
                "Kushtia": ["Bheramara", "Daulatpur", "Khoksa", "Kumarkhali", "Kushtia Sadar", "Mirpur"],
                "Magura": ["Magura Sadar", "Mohammadpur", "Shalikha", "Sreepur"],
                "Meherpur": ["Gangni", "Meherpur Sadar", "Mujibnagar"],
                "Narail": ["Kalia", "Lohagara", "Narail Sadar"],
                "Satkhira": ["Assasuni", "Debhata", "Kalaroa", "Kaliganj", "Satkhira Sadar", "Shyamnagar", "Tala"]
            },
            "Barishal": {
                "Barguna": ["Amtali", "Bamna", "Barguna Sadar", "Betagi", "Patharghata", "Taltali"],
                "Barishal": ["Agailjhara", "Babuganj", "Bakerganj", "Banaripara", "Barishal Sadar", "Gournadi", "Hizla", "Mehendiganj", "Muladi", "Wazirpur", "Barishal City", "Natullabad", "Sadar Road", "Band Road", "Rupatali", "Chawkbazar Barishal", "Amtala", "Kawnia", "Barishal Launch Ghat", "Circuit House Road"],
                "Bhola": ["Bhola Sadar", "Burhanuddin", "Char Fasson", "Daulatkhan", "Lalmohan", "Manpura", "Tazumuddin"],
                "Jhalokati": ["Jhalokati Sadar", "Kathalia", "Nalchity", "Rajapur"],
                "Patuakhali": ["Bauphal", "Dashmina", "Dumki", "Galachipa", "Kalapara", "Mirzaganj", "Patuakhali Sadar", "Rangabali"],
                "Pirojpur": ["Bhandaria", "Kawkhali", "Mathbaria", "Nazirpur", "Nesarabad", "Pirojpur Sadar", "Zianagar"]
            },
            "Rangpur": {
                "Dinajpur": ["Birampur", "Birganj", "Biral", "Bochaganj", "Chirirbandar", "Dinajpur Sadar", "Fulbari", "Ghoraghat", "Hakimpur", "Kaharole", "Khansama", "Nawabganj", "Parbatipur", "Dinajpur Town", "Gor-e-Shahid", "Munshipara", "Station Road Dinajpur", "Dhap Dinajpur"],
                "Gaibandha": ["Fulchhari", "Gaibandha Sadar", "Gobindaganj", "Palashbari", "Sadullapur", "Saghata", "Sundarganj"],
                "Kurigram": ["Bhurungamari", "Char Rajibpur", "Chilmari", "Kurigram Sadar", "Nageshwari", "Phulbari", "Rajarhat", "Raomari", "Ulipur"],
                "Lalmonirhat": ["Aditmari", "Hatibandha", "Kaliganj", "Lalmonirhat Sadar", "Patgram"],
                "Nilphamari": ["Dimla", "Domar", "Jaldhaka", "Kishoreganj", "Nilphamari Sadar", "Saidpur"],
                "Panchagarh": ["Atwari", "Boda", "Debiganj", "Panchagarh Sadar", "Tetulia"],
                "Rangpur": ["Badarganj", "Gangachara", "Kaunia", "Mithapukur", "Pirgachha", "Pirganj", "Rangpur Sadar", "Taraganj", "Rangpur City", "Dhap", "Station Road", "Jahaj Company", "Shapla Chottor", "Modern More", "Koiborta Para", "Lalbag", "Medhabibag"],
                "Thakurgaon": ["Baliadangi", "Haripur", "Pirganj", "Ranisankail", "Thakurgaon Sadar"]
            },
            "Mymensingh": {
                "Jamalpur": ["Bakshiganj", "Dewanganj", "Islampur", "Jamalpur Sadar", "Madarganj", "Melandaha", "Sarishabari"],
                "Mymensingh": ["Bhaluka", "Dhobaura", "Fulbaria", "Gaffargaon", "Gauripur", "Haluaghat", "Ishwarganj", "Muktagacha", "Mymensingh Sadar", "Nandail", "Phulpur", "Trishal", "Mymensingh Town", "Ganginagar", "Charpara", "Kewatkhali", "Shambhuganj", "Chorpara", "Notun Bazar Mymensingh", "Medical College Road"],
                "Netrokona": ["Atpara", "Barhatta", "Durgapur", "Khaliajuri", "Kalmakanda", "Kendua", "Madan", "Mohanganj", "Netrokona Sadar", "Purbadhala"],
                "Sherpur": ["Jhenaigati", "Nakla", "Nalitabari", "Sherpur Sadar", "Sreebardi"]
            },
            "Rajshahi": {"Bogura": ["Adamdighi", "Bogura Sadar", "Dhunat", "Dhupchanchia", "Gabtali", "Kahaloo", "Nandigram", "Sariakandi", "Shajahanpur", "Sherpur", "Shibganj", "Sonatola", "Bogura Town", "Satmatha", "Thana Road", "Jhauthala", "Khelafat Market", "Rangpur Road", "Jail Road"],
            "Bogura": ["Adamdighi", "Bogura Sadar", "Dhunat", "Dhupchanchia", "Gabtali", "Kahaloo", "Nandigram", "Sariakandi", "Shajahanpur", "Sherpur", "Shibganj", "Sonatola"],
                "Joypurhat": ["Akkelpur", "Joypurhat Sadar", "Kalai", "Khetlal", "Panchbibi"],
                "Naogaon": ["Atrai", "Badalgachhi", "Dhamoirhat", "Manda", "Mohadevpur", "Naogaon Sadar", "Niamatpur", "Patnitala", "Porsha", "Raninagar", "Sapahar"],
                "Natore": ["Bagatipara", "Baraigram", "Gurudaspur", "Lalpur", "Naldanga", "Natore Sadar", "Singra"],
                "Chapainawabganj": ["Bholahat", "Gomastapur", "Nachole", "Nawabganj Sadar", "Shibganj"],
                "Pabna": ["Atgharia", "Bera", "Bhangura", "Chatmohar", "Faridpur", "Ishwardi", "Pabna Sadar", "Santhia", "Sujanagar"],
                "Rajshahi": ["Bagha", "Bagmara", "Boalia", "Charghat", "Durgapur", "Godagari", "Mohanpur", "Paba", "Puthia", "Rajpara", "Shah Makhdum", "Tanore", "Rajshahi City", "Sahebbazar", "Ghoramara", "Laxmipur", "Padma Residential Area", "Uposhahar", "Kazla", "Binodpur Bazar", "Talaimari", "Bhandardaha"],
                "Sirajganj": ["Belkuchi", "Chauhali", "Kamarkhanda", "Kazipur", "Raiganj", "Shahjadpur", "Sirajganj Sadar", "Tarash", "Ullahpara"]
            }
        };